### ISSUE TITLE
Missing ExtractBurnin docs

### ISSUE THREAD

**Issue by tokejepsen** [ynput/ayon-documentation#144]
There was some documentation for `ExtractBurnin`; https://openpype.io/docs/pype2/admin_presets_plugins/#profile-burnins which needs to be documented in this project.

**Comment by MustafaJafar** [comment]
Closing this issue as there is merged PR for adding Extract Burnin Docs https://github.com/ynput/ayon-documentation/pull/181

Here's how it looks.
https://ayon.ynput.io/docs/addon_core_settings#extract-burnin

Please, Don't hesitate to open the issue again or create another issue if the docs missing any info about extract burnin.
