### ISSUE TITLE
Broken Links in docs

### ISSUE THREAD

**Issue by tweak-wtf** [ynput/ayon-documentation#183]
In the Nuke Artist docs under Review (https://ayon.ynput.io/docs/addon_nuke_artist/#review) the link pointing to the `Extract Review` docs is broken.

Currently points to https://ayon.ynput.io/docs/addon_nuke_artist/addon_core_settings#extract-review
But should point to https://ayon.ynput.io/docs/addon_core_settings/#extract-review

**Comment by MustafaJafar** [comment]
This issue is related to how the docs engine interprets the links. 
the solution is to write the extension of the file in the link:
e.g. this line

https://github.com/ynput/ayon-documentation/blob/f3719ff4f62b2805567927387c10c33d2c90bbf0/website/docs/addon_nuke_artist.md?plain=1#L333

should be 

```markdown
More info about [configuring reviews](addon_core_settings.md#extract-review).
```
