### ISSUE TITLE
Flame

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-documentation#274]
- [x] Update User doc
- [x] Update Admin doc
- [x] Draft for Forum post
- [x] Publish Forum post
- [x] Draft Discord announcement post
- [x] Publish Discord announcement post

**Comment by MustafaJafar** [comment]
This has been done. 
for reference: 
- [flame user docs](https://ayon.ynput.io/docs/addon_flame_artist)
- [flame admin docs](https://ayon.ynput.io/docs/category/flame)
- [forums announcement](https://community.ynput.io/t/ayon-pipeline-flame-addon/1831)
- [discord announcement](https://discord.com/channels/517362899170230292/802095378974638110/1293965568344330312)
