### ISSUE TITLE
Application Tools and Settings

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-documentation#277]
- [x] ~~Update User doc~~
- [x] Update Admin doc
- [x] Drafted for Forum+Discord posts
- [x] Publised on Forunm and Discord

**Comment by MustafaJafar** [comment]
We don't have user docs for application addon. maybe the only thing that is related is using the terminal and debug action.

**Comment by MustafaJafar** [comment]
all bullet points are done.
