### ISSUE TITLE
Web Launcher

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-documentation#279]
- [x] Update User doc
- [x] Update Admin doc
- [x] Drafted for Forum post
- [x] Drafted for Discord 
- [x] Publised on Forunm and Discord

~~Still need some dicision on where to add it: https://discord.com/channels/517362899170230292/1286457975489171549~~

**Comment by MustafaJafar** [comment]
PR for adding docs https://github.com/ynput/ayon-documentation/pull/287

**Comment by MustafaJafar** [comment]
all bullet points are done.
